# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=300)),
                ('profile_pic', models.ImageField(null=True, upload_to='pictures/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
