# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191016_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pic_image',
        ),
        migrations.AddField(
            model_name='image',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
