# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20191016_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
