# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-17 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20191016_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
