# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-18 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile_pic',
        ),
    ]
