# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-18 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_image_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_likes',
            field=models.ManyToManyField(default=False, null=True, related_name='likes', to='webapp.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_avatar',
            field=models.ImageField(null=True, upload_to='profile_avatar/'),
        ),
    ]
