# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-18 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20191018_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_image', models.CharField(max_length=250)),
                ('commented_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Image')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='webapp.Profile')),
            ],
        ),
    ]
