# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-18 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_likes',
        ),
    ]
