# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-18 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_remove_image_image_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_avatar',
        ),
    ]
