# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-19 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_comments_commented_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_image',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='person',
            new_name='posted_by',
        ),
    ]
