# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-20 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20191020_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
    ]
