# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-20 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_auto_20191020_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
